---
- name: Update GeoIP databases
  ansible.builtin.command: '{{ maxmind_update_binary }} -f {{ maxmind_update_configuration }}'
  register: geoipupdate_check
  failed_when: geoipupdate_check.rc > 1
  changed_when: false

- name: Restart cron
  ansible.builtin.service:
    name: "{{ 'cron' if ansible_os_family == 'Debian' else 'crond' }}"
    state: restarted
  when: not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker")
